### ISSUE TITLE
RuntimeError: Execution stopped while running CNM on DBLP dataset from the SNAP database

### ISSUE THREAD

**Issue by sarbajitsaha** [snap-stanford/snap#89]
The dataset is [DBLP dataset](https://snap.stanford.edu/data/com-DBLP.html).

Code - 

```
import snap,sys

UGraph = snap.LoadEdgeList(snap.PUNGraph, "../dataset/new_graph.txt",0,1)
CmtyV = snap.TCnComV()
modularity = snap.CommunityCNM(UGraph, CmtyV)
```

Error message - 
```
Traceback (most recent call last):
  File "cnm.py", line 5, in <module>
    modularity = snap.CommunityCNM(UGraph, CmtyV)
  File "/amd/hamsa.cs.iiests.ac.in/users1/student/be2014/sarbajits/Graph/CNM/snap.py", line 35949, in CommunityCNM
    return _snap.CommunityCNM(*args)
RuntimeError: Execution stopped: (0<=ValN)&&(ValN<Vals) [Reason:'Index:-2147403659 Vals:1073789418 MxVals:1298759680 Type:4TVecI7TTripleI4TFlt4TIntS2_EiE'], file /home/rok/include/glib/ds.h, line 469
```

Specifications of machine used - 
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Stepping:              7
CPU MHz:               1200.000
BogoMIPS:              3791.94
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-5,12-17
NUMA node1 CPU(s):     6-11,18-23
```
 If any more information is needed, please let me know. Thanks!

**Comment by roks** [comment]
The network is too large for this algorithm.
